# Generated by Django 3.1.5 on 2021-10-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
