# Generated by Django 3.2.8 on 2021-10-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_user_avata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avata',
        ),
    ]
