# Generated by Django 3.2.8 on 2021-11-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_remove_user_avata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_min', models.CharField(max_length=50)),
                ('score_max', models.CharField(max_length=50)),
                ('certificate', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='national',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='score_max',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_ans', models.CharField(max_length=50)),
                ('user_ans', models.CharField(max_length=50)),
                ('pre_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.pre_exercise')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.question')),
            ],
        ),
    ]
